title: Deepest.
description: deep learning and AI safety.
github_username: j-a-collins

# Email and twitter:
email: jackadamcollins@protonmail.ch
# twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Google Analytics ID:
# google_analytics:

# Theme:
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
